// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB94lM3bY7J67hmOOPXlvu_o1qGcyLcRY',
    appId: '1:680204930410:web:25f86fff32f43aef0f6913',
    messagingSenderId: '680204930410',
    projectId: 'hiwkhao-set',
    authDomain: 'hiwkhao-set.firebaseapp.com',
    storageBucket: 'hiwkhao-set.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7fLdoEz51b3sOaoGsmePJHIeUK8RuA8g',
    appId: '1:680204930410:android:6faeedf997bca6ea0f6913',
    messagingSenderId: '680204930410',
    projectId: 'hiwkhao-set',
    storageBucket: 'hiwkhao-set.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnw9Ndn6fLMOVulptk3-VlvmSvbDl6L4Q',
    appId: '1:680204930410:ios:6eaf7b974ccda3c90f6913',
    messagingSenderId: '680204930410',
    projectId: 'hiwkhao-set',
    storageBucket: 'hiwkhao-set.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnw9Ndn6fLMOVulptk3-VlvmSvbDl6L4Q',
    appId: '1:680204930410:ios:8482089348dbd6670f6913',
    messagingSenderId: '680204930410',
    projectId: 'hiwkhao-set',
    storageBucket: 'hiwkhao-set.appspot.com',
    iosBundleId: 'com.example.untitled4.RunnerTests',
  );
}
